### ISSUE TITLE
调用quitWithCallback闪退，必现

### ISSUE THREAD

**Issue by ylrs** [leancloud/objc-sdk#109]
[self.conversation quitWithCallback:^(BOOL succeeded, NSError * _Nullable error) {
        
    }];
拿到conversation以后调用这段代码，会闪退

**Comment by tang3w** [comment]
请打印出 conversation.imClient.clientId 的值。如果为 nil，请问 conversation 是如何获取到的？请提供一下复现问题的代码片段或者 demo。

**Comment by tang3w** [comment]
没有进一步回复，先关闭了。如有有问题再反馈。
