### ISSUE TITLE
conversationQuery 不能查询到最新的聊天室

### ISSUE THREAD

**Issue by BrikerMan** [leancloud/objc-sdk#114]
## Base Info for this issue 
 1. sdk_version: v3.7.1
 2. App-ID: vKX4MuwjxME7qxuJC1N88nr7
 3. Language：Swift
 4. iOS System Version：iOS10
 5. Prototype（是否是真机）：YES
 6. Issue Type：Bug

## 1. How to repeat the problem.
设备 A 启动 demo 然后进入 [demo](https://github.com/BrikerMan/ChatKit-Swift-demo) 进入聊天室列表。
设备 B 启动 demo 创建新聊天室， 这时候设备 A 进行 query 操作并不能找到设备 B 新创建的聊天室。

## 2. Please help me in this way.
设备 A 能找到新聊天室。

## 3. Here is a Demo. 
https://github.com/BrikerMan/ChatKit-Swift-demo

关键代码
每 2.5 秒更新一次聊天室列表
``` swift
    func queryTransientConversations() {
        let query = ChatClient.conversationQuery()
        query.whereKey("tr", equalTo: true)
        query.order(byDescending: "updatedAt")
        query.findConversations { (result, error) in
            
            print("| Query Results | - \(result?.count)")
            
            if let result = result as? [AVIMConversation] {
                self.conversations = result
                DispatchQueue.main.async {
                    self.tableView.reloadData()
                }
            } else {
                Hud.showError(error: error?.localizedDescription)
            }
        }
    }
```

创建聊天室
```
ChatClient.createConversation(withName: self.textField!.text!, clientIds: [], attributes: nil, options: AVIMConversationOption.transient, callback: { (coversation, error) in
                    if let error = error {
                        Hud.showError(error: error.localizedDescription)
                    } else {
                        let vc = LCCKConversationViewController(conversationId: coversation?.conversationId)
                        self.navigationController?.pushViewController(vc!, animated: true)
                    }
                })
```

**Comment by ChenYilong** [comment]
请问A和B是同一个ClientId吗？是否开启了单点登录？

**Comment by BrikerMan** [comment]
不是，两个 ID。

**Comment by ChenYilong** [comment]
都在一个群里才能查到。

**Comment by BrikerMan** [comment]
@ChenYilong 不对啊，那为什么app启动时候即使不再群里也能查到？或者 B 创建后 A 重新启动就可以看到。

**Comment by ChenYilong** [comment]
这个主要根据你的查询条件而定，一般情况下的需求，是不会查询那些自己不是成员的conversation。

**Comment by ChenYilong** [comment]
conversationQuery的limit默认是10，你可以根据需要，调整得大点。

**Comment by BrikerMan** [comment]
我的问题是，A启动后 其他设备新建聊天室 A 并不能查询到。但是如果此时 A 重新启动了，就可以查询到。总得聊天室数量并没有达到10 。

**Comment by ChenYilong** [comment]
我看你只查询暂态聊天室吗？你创建的也是暂态聊天室吗？

**Comment by BrikerMan** [comment]
嗯嗯，是的。创建也是暂态。

**Comment by ChenYilong** [comment]
贴下日志吧，贴下请求和返回的日志，返回是空？

**Comment by BrikerMan** [comment]
@ChenYilong 看了半天 log 不知道该发那一段， 可以直接下载 [DEMO](https://github.com/BrikerMan/ChatKit-Swift-demo) 试试。麻烦啦~

**Comment by ChenYilong** [comment]
这里是因为服务端做的一个特殊处理：

当这样初始化时，where语句是一个空的：

 ```Objective-C

    AVIMConversationQuery *query1 = [client conversationQuery];
   [query findsConversation...];

 ```

当服务端发现where语句是空的话，会默认的把它转化成members包含当前client的一个where语句。这也就是为什么query1会返回Id：204相关的对话。而且不会返回暂态对话、系统对话，因为他们的members字段都是nil。


但是当where语句包含内容，不管是什么内容，or条件也好，lm大于0也好，“members包含当前client”这个条件不会默认加上，这也就是为什么你上面的lm>0的条件会将跟204无关的对话也返回回来。

综上可以总结出来：

conversation query 的where查询，如果发送一个空的，会默认返回与当前client相关的非暂态对话、非系统对话。但是如果添加了任意的where语句，比如lm字段大于0，就会将所有lm字段大于0 的会话返回，包括暂态对话、非系统对话。 同时一个空的where语句，搭配or语句查询时，空where语句所代表的筛选出非暂态对话、非系统对话，这个意义也将不会起作用。仅仅是or之后的内容在筛选。

**Comment by tang3w** [comment]
目前如果要查询所有对话，包括聊天室。需要如下构造查询条件：

```objc
AVIMClient *client = {{YOUR_CLIENT}};

AVIMConversationQuery *queryForAllTransientConversations = [client conversationQuery];
AVIMConversationQuery *queryForAllNonTransientConversations = [client conversationQuery];

[queryForAllTransientConversations whereKey:@"tr" equalTo:@(YES)];

AVIMConversationQuery *queryForAllConversations = [AVQuery orQueryWithSubqueries:@[
    queryForAllTransientConversations,
    queryForAllNonTransientConversations
]];

[queryForAllConversations findConversationsWithCallback:^(NSArray *conversations, NSError *error){
    /* Your code */
}];
```

先关闭 issue 了，有问题请再反馈。
