### ISSUE TITLE
IM单元测试增强

### ISSUE THREAD

**Issue by ChenYilong** [leancloud/objc-sdk#116]
发现个好东西，自动在多个 iOS 模拟器上运行 XCTest 测试，想试试用来做IM的单元测试。

https://github.com/plu/pxctest

调研下。

**Comment by tang3w** [comment]
想用它来测试哪些聊天场景？它可以控制应用的前后台切换吗？

**Comment by tang3w** [comment]
@ChenYilong 这个 issue 目前是什么状态？如果短期内不计划实现或意义不大，就关掉吧。

**Comment by ChenYilong** [comment]
可以先关掉，慢慢完善。
