### ISSUE TITLE
AVUser.current()!.fetch() 之后 sessionToken 消失

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#127]
3.7.1 中没有问题，3.8.1 中出现了该问题
以下代码填 App Key 进去就可以重现：
```
        AVOSCloud.setApplicationId("nWV9ebO1JMUIE5K4gBS1i1MA", clientKey: "")
        
        
        AVUser.logInWithUsername(inBackground: "123", password:"123", block: { (user, error : Any?) in

            if error == nil {
                
                print("sessionToken---"+String(describing: AVUser.current()!.sessionToken))
                
                AVUser.current()!.fetch()
                print("-----------------------")
                // sessionToken 消失了
                print("sessionToken---"+String(describing: AVUser.current()!.sessionToken))
                
                
            }
            
        })
```

**Comment by tang3w** [comment]
可能需要了解一下使用场景是什么。

服务端说不存在用户登录后再 fetch 的场景。并且由于安全因素，服务端不希望在 fetch 时返回 sessionToken。这样一来，SDK 不会认为这是一个 bug，也不准备对 AVUser 的 sessionToken 做特殊处理。

如果应用希望 fetch 后不丢失 sessionToken，请自行负责缓存 sessionToken，并在 fetch 后重新赋值给 currentUser。

**Comment by nicecui** [comment]
用户反馈他们有一些功能并不是直接使用 SDK 访问的 API，而是通过自己的后端服务器来访问我们的 API，当他们通过自己的服务端去更新用户数据的时候，客户端就需要去 fetch 用户的新数据。
fetch 之后 SDK 能否保留 sessionToken 的缓存？

**Comment by tang3w** [comment]
SDK 会在 fetch() 成功后，抹掉 object 中的所有数据。服务端出于安全原因不希望在 fetch() 接口中返回 sessionToken，除非 SDK 对 sessionToken 做特殊处理，但这样有些代价。因此，如果用户需要针对这种特殊场景做特殊处理，即：fetch 前先获取 sessionToken，fetch 完之后，将 sessionToken 设置回去。

**Comment by nicecui** [comment]
讨论一番之后还是决定加上 sessionToken：
https://leanticket.cn/t/leancloud/2263
https://forum.leancloud.cn/t/user/12668/14

**Comment by zhuozhuo** [comment]
兄弟这个问题很严重，今天整个移动端开发组被点名批评。希望下次更新能兼顾下旧的SDK，这么大的隐患能否告知下。

**Comment by tang3w** [comment]
的确是我们的疏忽。这是在实现另一个新功能时引入的问题，造成不兼容的行为，带来的不便深表歉意。

**Comment by tang3w** [comment]
已在 v3.10.0 中修复。

**Comment by youngsherlee** [comment]
移动端更新到最新3.10.0问题依旧存在，ser.sessionToken为空

**Comment by tang3w** [comment]
请上传一个复现该问题的 demo。

**Comment by youngsherlee** [comment]
应用重新删除重新安装就OK了...之前的User一直没有退出过，所以sessionToken一直是空的...

**Comment by tang3w** [comment]
好的，有问题随时反馈。
