### ISSUE TITLE
建议删掉 [AVOSCloud useAVCloudUS] 相关代码

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#134]
已 deprecated 的还有：
```
    [AVOSCloud useAVCloud];
    [AVOSCloud useAVCloudCN];
```

建议都一并删除，因为有新的接口取而代之。

详见：https://forum.leancloud.cn/t/topic/12594/13

**Comment by tang3w** [comment]
希望让作废的接口保留更长一段时间。作废信息可以引导用户尽快切换成新接口。等大部分用户都切换成新接口时，咱们再删除吧。
