### ISSUE TITLE
3.8.2版本提交审核还是报IPv6的问题

### ISSUE THREAD

**Issue by liubiqu** [leancloud/objc-sdk#136]
3.8.1提交的被拒，升级到3.8.2还是一样的问题，只能恢复到3.7.1可以提交通过

**Comment by tang3w** [comment]
请提供一下拒绝的原因。

**Comment by liubiqu** [comment]
Thank you for your resubmission.


Performance - 2.1


We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.2 on Wi-Fi connected to an IPv6 network.

The login process took indefinite period of time. 

We've attached screenshot(s) for your reference.

**Comment by tang3w** [comment]
可能需要在本地模拟的 IPv6-only 网络中测试一下，看看具体原因是什么。

**Comment by ChenYilong** [comment]
不一定是IPv6的问题，也可能是国内的APPID，在国外访问国内服务器，访问失败造成的。

**Comment by liubiqu** [comment]
具体的原因我也不清楚，我退回版本再打包提交，就通过审核了，不知道其他人有没有碰到类似的问题

**Comment by tang3w** [comment]
暂时没有其他用户反馈使用 v3.8.2 审核被拒绝的问题。我们再观察一下，如果有类似反馈，我们会立即处理。

**Comment by liszd** [comment]
最近3.10.0提交审核还是报IPv6的问题。

**Comment by tang3w** [comment]
@liszd SDK 目前支持 IPv6-only。苹果拒绝的原因不一定是在 IPv6-only 网络环境下无法访问，也有可能是国内 DNS 劫持的问题。您可以自己搭建一个 IPv6-only 网络环境测试一下，如果测试没有问题，可以向苹果申诉。

**Comment by liszd** [comment]
@tang3w 我已经测了IPv6的环境可以访问，也拍了视频给他。但是他就是说他那不行，不给我通过，我已经和他耗了10天了😢

你们有什么针对措施吗，每次这样好心累啊

**Comment by tang3w** [comment]
能否向苹果的技术人员要一份详细的网络请求日志，找一下具体错误原因。看看是否是 DNS 劫持，如果是确认是 DNS 劫持，SDK 未来会利用 HTTP DNS 来改善这种情况。可以先尝试向苹果索要一些网络诊断信息。
