### ISSUE TITLE
请教 ios sdk 苹果ATS https 的问题

### ISSUE THREAD

**Issue by SunLn** [leancloud/objc-sdk#142]
查询了贵公司的社区论坛，发现 https://forum.leancloud.cn/t/https/12391  答复是sdk一直都是 https的，但我们公司产品用的是一个[cordova-plugin-leanpush](https://github.com/BenBBear/cordova-plugin-leanpush)社区插件 ，上一次更新已经是9个月之前，然后我仔细看里面引用的[framework] (https://github.com/BenBBear/cordova-plugin-leanpush/tree/master/src/ios/Frameworks) 更是 2年之前的版本(最近的commit是2015-07-13），我想查这个版本的sdk 版本号，但没有找到。所以想麻烦确认一下：
1、该版本已经支持https了吗
2、贵公司是否有更好的cordova社区推荐产品(我是没有查到，囧)

谢谢了

**Comment by tang3w** [comment]
SDK 从最开始就是完全使用 HTTPS 的，只是文件存储可能会产生 HTTP 的连接，而这个问题可以在 LeanCloud 控制台中开启一个选项来解决。因此，不用担心 HTTPS 的问题。不过可能需要注意 IPv6-only 的兼容性，两年前的版本不支持 IPv6-only 网络环境。

很遗憾，Cordova 社区到目前为止没有太多可用的 LeanCloud 相关插件，无法推荐。

**Comment by SunLn** [comment]
谢谢你的热心答复，解决了我的困扰。
