### ISSUE TITLE
建议崩溃报告提供更详细的信息

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#15]
问题来源：
https://leanticket.cn/t/leancloud/2321?show=all

之前也有用户遇到过同样的问题，App 上线崩溃后只能从崩溃报告中看出有限的信息，这个时候用户也无法（很困难）重现并定位问题，我们多次和用户沟通也没有结果。消耗了时间成本却没有解决问题。

所以崩溃报告是否可以做的更详细些？比如可以看到具体什么请求造成了这样的崩溃。

**Comment by nicecui** [comment]
拜访用户的时候，用户也提出了同样的问题。用户表示 Android 的崩溃报告很好用，可以定位到具体哪一行代码以及具体错误，但是 iOS 的崩溃报告看到的信息也很有限。

**Comment by tang3w** [comment]
这与系统和第三方错误分析产生的信息缺乏有关，要替换目前的错误分析报告的代价很大。需要调研一下。

**Comment by nicecui** [comment]
再提供一个案例支撑：
https://forum.leancloud.cn/t/leancloud/11500

**Comment by zapcannon87** [comment]
NO NEED
