### ISSUE TITLE
一个崩溃问题,望早日修复

### ISSUE THREAD

**Issue by Lafree317** [leancloud/objc-sdk#153]
![2017-01-06 6 49 16](https://cloud.githubusercontent.com/assets/13520567/21716051/018bb518-d443-11e6-9478-1274e247f4d9.png)
![2017-01-06 7 01 01](https://cloud.githubusercontent.com/assets/13520567/21716056/05fa7652-d443-11e6-9519-d28f22d2109d.png)

**Comment by tang3w** [comment]
错误栈看上去是内存分配出错，请贴出原始日志。
