### ISSUE TITLE
微信不支持 sso 登录

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#154]
详见：https://leanticket.cn/t/leancloud/3558

另外，请 @tang3w 检查下，微博和 QQ 是不是依旧支持 sso 登录？如果不行的话，对应的文档也需要下掉。

**Comment by tang3w** [comment]
从源码来看，微博和 QQ 是支持的。微信由于需要让用户接入微信的 SSO SDK，暂时建议用户通过微信的登录 SDK 拿到 authData 来登录。
