### ISSUE TITLE
关于 iOS 错误码的优化建议

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#158]
## 现状
1、目前在错误码页面，iOS 有很多其他的报错说明，整体不统一，用户体验不是很好，如下面的：
iOS 的 AVConstants。
iOS SDK 在进行 WebSocket 通信过程中，相关的状态码请参考 RFC 6455 · Status Codes。
iOS v3.1.5 及之后的版本，与网络请求操作相关的错误码，比如 28 表示请求超时、7 表示连接服务器失败，请参考 libcurl error codes。
2、有时候会有一些意义不明的报错，如 Error Infomation Unknown。
来源 https://leanticket.cn/t/leancloud/3540

## 建议
1、是否可以给 AVConstants 一个统一的编码？让用户知道看到这个编号时，知道要去单独点开 AVConstants 的页面。RFC 6455 · Status Codes 和 libcurl error codes 也是同理。
2、改善模糊不清的报错说明。

@tang3w @ChenYilong

**Comment by tang3w** [comment]
* AVConstants 与 REST API 的 error code 是一一对应的，只是赋予了枚举名。
* RFC 6455 是实时通信中的状态码，目前文档上列举了业务相关了的错误码，非业务相关的代码让用户参考 RFC 应该是正确的引导。
* libcurl error codes 的链接对新版 objc-sdk 是过时的，因为网络库不再使用 libcurl 了，可以去掉。

**Comment by tang3w** [comment]
出现 Error Infomation Unknown 的情况有两种：

1. 用户使用了保留字段，导致 SDK 解析出错。这种情况下的确应该有一个明确提示。
2. 服务端在错误信息中只返回了 code 字段，但没有 error 字段。

SDK 可以改进第一种情况；第二种情况如果存在，需要服务端改进错误提示。

**Comment by tang3w** [comment]
Published in v4.0.0
