### ISSUE TITLE
在OSX下编译报错：duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by luoxiao1115** [leancloud/objc-sdk#173]
麻烦看看为什么？

duplicate symbol _OBJC_IVAR_$_AFXMLDocumentResponseSerializer._options in:
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AFNetworking/libAFNetworking.a(AFURLResponseSerialization.o)
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AVOSCloud/libAVOSCloud.a(LCURLResponseSerialization.o)
duplicate symbol _OBJC_CLASS_$_AFXMLDocumentResponseSerializer in:
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AFNetworking/libAFNetworking.a(AFURLResponseSerialization.o)
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AVOSCloud/libAVOSCloud.a(LCURLResponseSerialization.o)
duplicate symbol _OBJC_METACLASS_$_AFXMLDocumentResponseSerializer in:
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AFNetworking/libAFNetworking.a(AFURLResponseSerialization.o)
    /Users/luoxiao/Library/Developer/Xcode/DerivedData/LXFanyi-gldlqqdobesqvugkqmuynraxfjxs/Build/Products/Debug/AVOSCloud/libAVOSCloud.a(LCURLResponseSerialization.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tang3w** [comment]
可能是旧版本 SDK 中网络请求的部分代码和应用依赖的 AFNetworking 冲突，请告知 SDK 版本号。

**Comment by tang3w** [comment]
确实有冲突，我们会尽快修复，在下个版本中发布。

**Comment by tang3w** [comment]
已在 v4.0.1 中修复。

**Comment by luoxiao1115** [comment]
好的，谢谢
