### ISSUE TITLE
AVIMWebSocketWrapper重连属性没有被重置

### ISSUE THREAD

**Issue by wells1013** [leancloud/objc-sdk#177]
```
#pragma mark - ping timer fierd
- (void)timerFired:(id)sender {
    if (_lastPongTimestamp > 0 && [[NSDate date] timeIntervalSince1970] - _lastPongTimestamp >= 5 * 60) {
        [self closeWebSocketConnection];
        return;
    }
    
    if (_webSocket.readyState == AVIM_OPEN) {
        [self sendPing];
    }
}
```

这里 _lastPongTimestamp 超时后，关闭连接下次进来还是超时！以后一直超时，ping,pong 将失效, 网络连接就一直处于close， open 来回切换的过程。

_waitingForPong 估计也不会修改。

**Comment by tang3w** [comment]
谢谢您的反馈，请问有没有复现该问题的步骤或场景？

**Comment by wells1013** [comment]
我在` if (_lastPongTimestamp > 0 && [[NSDate date] timeIntervalSince1970] - _lastPongTimestamp >= 5 * 60)` 设置断电，等待结果为真的时候，ok 后面就重现了。

如果应用中要重现，可能要网络配合
在init 方法里_lastPongTimestamp 已经赋值， _lastPongTimestamp >0 为真， 如果在第一次连接的时候，webSocketDidOpen 来的很迟了 >5*60, 就会出现了。

还有我们线上app 进入聊天室，但是发送消息的时候，告诉我4401 不在此回话中，不知道会不会跟这个不断重连有关系？

**Comment by wells1013** [comment]
是不是应该加上 `_waitingForPong` 是否在ping pong中的判断呢？
![image](https://cloud.githubusercontent.com/assets/5172252/22963029/87728d52-f38b-11e6-957d-5f84bd5f8e3c.png)
上面只是我猜测的可能重现的步骤。
在运行中，光判断 `_lastPongTimestamp`可能会有问题，调用reconnect方法这个时候好像也有问题的。
`now - _lastPingTimestamp > _timeout` [line 677]这个时候就会出现进不来，_lastPongTimestamp 就不会改为0.

这里的重现步骤我不知道，只是从代码逻辑上感觉有点漏洞。

**Comment by BinaryHB** [comment]
另一位同学也遇到类似的问题： https://forum.leancloud.cn/t/im-5/13439 @tang3w

**Comment by tang3w** [comment]
收到，重连逻辑可能是有问题。我们会尽快排查。

**Comment by tang3w** [comment]
在 v4.3.0 中做了一些优化，测试已解决。
