### ISSUE TITLE
How to support localization?

### ISSUE THREAD

**Issue by Tinghui** [leancloud/objc-sdk#180]
The device's language is zh_CN, but the error info which returned by AVCloud API was not localized. 

Please see the NSLocalizedDescription field in the error info:
Error Domain=AVOS Cloud Error Domain Code=101 "no results matched the query" UserInfo={error=no results matched the query, NSLocalizedDescription=no results matched the query, code=101}

So there is my question: how to support localization in AVCloud?

**Comment by tang3w** [comment]
Sorry, we do not support the internationalization of error message recently. A possible approach is translating the error code to your own internationalized message.
