### ISSUE TITLE
Block 为nil 的时候崩溃了

### ISSUE THREAD

**Issue by wells1013** [leancloud/objc-sdk#184]
`AVPaasClient`类中， `performRequest:saveResult:block:retryTimes:` 方法，如果block 为空的时候，失败的时候就崩溃了。

`[[AVPaasClient sharedInstance] postObject:@"fileCallback" withParameters:parameters block:nil];`
查询文件的时候就是传的空。

![image](https://cloud.githubusercontent.com/assets/5172252/23603669/02af4d20-0291-11e7-951d-3d51021144b0.png)

**Comment by tang3w** [comment]
谢谢反馈，我们会尽快修复这个问题。

**Comment by tang3w** [comment]
Solved in v4.2.0
