### ISSUE TITLE
解决 _lctype 属性 resolve 失败的问题

### ISSUE THREAD

**Issue by tang3w** [leancloud/objc-sdk#192]
有用户报告 AVIMTypedMessageObject 的 `set_lctype:` 实例方法偶尔找不到，引起 crash。这些属性没有必要作为 dynamic 来实现。因此准备消除 dynamic，把 getter 和 setter 分别 forward 到 `objectForKey:` 和 `setObject:forKey:` 上面。

**Comment by artern** [comment]
这个问题何时能够得到修复？？

**Comment by tang3w** [comment]
预计本周会发布新版本。

**Comment by tang3w** [comment]
Solved in 4.3.0
