### ISSUE TITLE
多语言适配问题的建议

### ISSUE THREAD

**Issue by zhuozhuo** [leancloud/objc-sdk#203]
Hi，
    SDK中是否已经做了多语言适配呢？因为我发现有些提示是英文有些提示是中文和系统语言无关。多语言适配是否可以加入SDK中呢？

**Comment by tang3w** [comment]
你好，SDK 没有做多语言适配，提示是服务端返回的。建议判断 error code，然后给出应用自定义的国际化提示。

**Comment by zhuozhuo** [comment]
[error code详解](https://leancloud.cn/docs/error_code.html)错误码都在这里了么？因为我发现中文的错误提示有些在你们的错误码中是找不到的，而我们发现这个问题也是大都通过国外客户反馈过来的。例如:请不要往同一个邮件地址中发送太多邮件。

**Comment by tang3w** [comment]
错误码在页面中找不到的问题请 @killme2008 看看。

**Comment by tang3w** [comment]
@zhuozhuo 请给出在页面中找不到的错误码和错误提示。

**Comment by zhuozhuo** [comment]
暂时就知道这一个错误提示：请不要往同一个邮件地址中发送太多邮件。

**Comment by tang3w** [comment]
错误码未来可能会在文档中补充，issue 先关闭了。
