### ISSUE TITLE
Xcode 8.3 一大堆警告

### ISSUE THREAD

**Issue by zhuozhuo** [leancloud/objc-sdk#204]
Hi，
    Xcode 8.3下编译出现一大堆警告提示。希望尽快Fix！

**Comment by tang3w** [comment]
谢谢反馈，我们尽快修复。

**Comment by tonycph** [comment]
问题是否依然存在？

**Comment by tang3w** [comment]
你好，这个警告产生的原因是 protobuf runtime 的问题，这个 protobuf runtime 会在 v7 中以外部依赖的方式存在，这样会消除警告。一直没有动它的原因是目前需要做大量重命名符号的工作，因此在下个大版本中决定以外部依赖的方式存在。如果你是通过 CocoaPods 集成，可以使用 inhibit_all_warnings! 命令来暂时消除警告。

**Comment by zhuozhuo** [comment]
下个大版本大概什么时候更新呢？

**Comment by tang3w** [comment]
> 下个大版本大概什么时候更新呢？

计划在 7 月下旬，目前已经在 https://github.com/tang3w/objc-sdk/tree/v6 中完成了部分工作。
