### ISSUE TITLE
奔溃问题。

### ISSUE THREAD

**Issue by wells1013** [leancloud/objc-sdk#209]
IM用的版本是 `4.1.0`

![image](https://cloud.githubusercontent.com/assets/5172252/25034563/09629418-211a-11e7-9b3b-9d64ac492359.png)

**Comment by tang3w** [comment]
请检查原始日志，看看是否有异常描述。

**Comment by tang3w** [comment]
已经在 v4.3.0 中重写 LCRouter 的实现。
