### ISSUE TITLE
lean engine hook after save conversation 在Chatkit通过peerId打开后不执行

### ISSUE THREAD

**Issue by ghost** [leancloud/objc-sdk#210]
如果是实现创建的conversation， after save 会执行，Chatkit中通过peerId打开对话，对话成功创建，但是after save hook没有执行

**Comment by tang3w** [comment]
因为 ChatKit 会尽量尝试查询已创建的对话，如果找到就不创建了，after save hook 也就不会执行。

**Comment by liyukuang** [comment]
这个我知道，但是第一次创建的时候也没有得到执行。

**Comment by zapcannon87** [comment]
no need
