### ISSUE TITLE
IPV6 苹果审核不通过

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#23]
https://forum.leancloud.cn/t/sdk/9946

**Comment by tang3w** [comment]
这两天一直跟用户的沟通。问题现象是在本地模拟的 IPv6 网络环境下，SDK 是能访问 REST API 的，一旦连接国外的 VPN，网络访问就会失败。另外有些用户还在使用旧版本 SDK，升级新版本即可。其中一个用户用的是最新版本，但从苹果提供的拒绝反馈来看，只有个别 API 有这种现象。具体造成的原因还不清楚，还在进一步沟通当中。

**Comment by tang3w** [comment]
许多用户用 v3.3.5 版本的 SDK 已经审核通过了，怀疑审核不通过的 app 依赖了其他不兼容 IPv6-only 的第三方库。

**Comment by nicecui** [comment]
这个看起来也有苹果方面的原因：
https://www.v2ex.com/t/287700
还有其他类似的情况：
http://www.cocoachina.com/bbs/read.php?tid-1684570-page-1.html

**Comment by tang3w** [comment]
有用户在论坛中描述了应用审核被拒绝的遭遇和解决办法： https://forum.leancloud.cn/t/sdk/9946 。

**Comment by tang3w** [comment]
未来会增加防 DNS 劫持的特性，应该会改善这个问题。先关闭该工单。
