### ISSUE TITLE
卡死主线程

### ISSUE THREAD

**Issue by wells1013** [leancloud/objc-sdk#247]
![image](https://cloud.githubusercontent.com/assets/5172252/25989144/a29c0fa0-372d-11e7-9efd-82eb91910b70.png)
如图，开发环境卡死主线程。

**Comment by tang3w** [comment]
麻烦展开一下 Thread 20 的 backtrace。

**Comment by zapcannon87** [comment]
已在 v8.0.6 中修复该问题。
