### ISSUE TITLE
能否把删除本地消息的API放到public呢

### ISSUE THREAD

**Issue by DSKcpp** [leancloud/objc-sdk#248]
业务需要使用 `[LCIMMessageCache deleteMessages:forConversationId:]` 接口
而且 `[LCIMMessageCacheStore updateBreakpoint:forMessage:]` 会crash，因为没有nextMessage

**Comment by tang3w** [comment]
为了保证服务端和客户端消息记录的一致性，目前暂时没有计划开放出来。我们正在开发一个更好的机制来解决消息删除的问题。如果您确实有这个需求，请自行 public 到您的项目中。

**Comment by zapcannon87** [comment]
no need
