### ISSUE TITLE
Xcode 8.3.2   一大堆警告 今天新pod的

### ISSUE THREAD

**Issue by tonycph** [leancloud/objc-sdk#259]
感谢大大

问题是否依然存在？我创建一个新的项目，但还是一堆警告
一些警告不敢自行修改，例如改变return statement 的

警告包括
![screen shot 2017-05-22 at 3 27 51 pm](https://cloud.githubusercontent.com/assets/10664603/26296893/405d12b6-3f03-11e7-90ba-d6fdd37d879e.png)

**Comment by tonycph** [comment]
Download the sdk from there [](https://github.com/leancloud/objc-sdk/releases) solve the issues.

**Comment by tang3w** [comment]
是的，注释的问题在之前有个版本已经修复了。
