### ISSUE TITLE
LiveQuery哪去了?

### ISSUE THREAD

**Issue by VianPan** [leancloud/objc-sdk#289]
如题, Cocoapods都search不到, 刚想用这功能, 咋整?

**Comment by tang3w** [comment]
可能是本地 CocoaPods 仓库没有更新，请执行 `pod repo update` 更新一下在搜索。

**Comment by VianPan** [comment]
repo更新也是没用, 重建索引后找到了
rm -rf ~/Library/Caches/CocoaPods/search_index.json
在重新搜索

**Comment by VianPan** [comment]
另外, 没有swift版本?

**Comment by tang3w** [comment]
现在还没有 Swift 实现。Objective-C SDK 可以桥接到 Swift 中使用。
