### ISSUE TITLE
AVIMClient 单例时编译失败

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#3]
可以重现的 Demo：
[SignupTestD.zip](https://github.com/leancloud/objc-sdk/files/365169/SignupTestD.zip)

症状如图：
![_2016-07-15_11-02](https://cloud.githubusercontent.com/assets/10130959/16863220/0c994050-4a83-11e6-9458-c9227c11e000.png)

**Comment by tang3w** [comment]
下个版本 v3.4 会修复该问题。
