### ISSUE TITLE
文件名问题

### ISSUE THREAD

**Issue by SLboat** [leancloud/objc-sdk#30]
下载改到这里以后,下了watchos的库,拉到Xcode里死活不工作,后来改了文件名才工作,必须去掉那个watchos的后面文件名.

**Comment by tang3w** [comment]
谢谢反馈，framework 的文件名是可以自由修改的。请问具体的编译错误是什么？

**Comment by tang3w** [comment]
这里的确应该去掉平台后缀，使用路径来区分。可能需要换一个地方来存放这些 frameworks。

**Comment by tang3w** [comment]
计划不再发布 frameworks，用户可通过自动编译脚本自行打包。参考 [Wiki](https://github.com/leancloud/objc-sdk/wiki/Installation) 的说明。
