### ISSUE TITLE
手机发热

### ISSUE THREAD

**Issue by sxsdjkk** [leancloud/objc-sdk#304]
pod 'AVOSCloud','<= 3.1.0'
pod 'AVOSCloudCrashReporting','<= 3.1.0'

3.1.0正常不发热，升级5.0,6.1都会发热，使用过程中，会突然开始发热。好多用户反馈，版本升级后发热明显。现在只能使用3.1.0版本了。

**Comment by tang3w** [comment]
请 profile 一下，看看是什么代码消耗了太多 CPU。然后将 profile 的报告导出一份，提供给我们。

**Comment by sxsdjkk** [comment]
并不是每次都会重现。

**Comment by tang3w** [comment]
请尝试找一下复现路径，或者调试时尽可能用 profile 功能来调试，待出现发热的时候，再将报告导出。
