### ISSUE TITLE
改进美国节点 AVFile 上传失败情况下的报错提示

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#316]
来源：https://forum.leancloud.cn/t/code-403-forbidden-to-delete-by-class-file-permissions/15390/2

原因：在上传 S3 文件失败时，iOS SDK 会主动清理文件，而 File 表权限恰好不允许删除，所以报错了。

优化：用 fileCallback 来改进一下。

**Comment by tang3w** [comment]
Solved in v7.0.0
