### ISSUE TITLE
开发环境遇到一次崩溃

### ISSUE THREAD

**Issue by wells1013** [leancloud/objc-sdk#336]
![image](https://user-images.githubusercontent.com/5172252/29545369-7b46fecc-8720-11e7-9806-8c59a58b9250.png)
![image](https://user-images.githubusercontent.com/5172252/29545382-91c3b668-8720-11e7-985a-6b5a49c50cf0.png)
搞不懂 是什么原因？
不是必然出现 

版本: AVOSCloudIM 7.0.0

**Comment by wells1013** [comment]
![image](https://user-images.githubusercontent.com/5172252/29555174-5df0879c-8754-11e7-8600-f21d466bbb0a.png)
线上版本遇到相仿的奔溃日志。

**Comment by tang3w** [comment]
看起来是 SDK 依赖的 WebSocket 库没有管理好内存，出现了野指针，以至于这个指针所指向的位置恰好是一个 UIFont 实例。在调用其 openConnection 时出现异常。我们根据您提供的信息调查一下。

**Comment by wells1013** [comment]
![image](https://user-images.githubusercontent.com/5172252/29700681-5df80638-8999-11e7-8a6c-c5ab23ffd8a5.png)

```
- (void)networkDidBecomeReachable {
    [self reopenWebSocketConnection];
}
```
调用两次的时候出现的，刚才又出现这个bug

**Comment by wells1013** [comment]
今天用断点跟了下， 创建 `AVIMWebSocketWrapper` 的时候， 
![image](https://user-images.githubusercontent.com/5172252/29756141-edda62dc-8bd3-11e7-9d3e-4c48f913f21c.png)
就有个网络链接的后台的回调，
![image](https://user-images.githubusercontent.com/5172252/29756154-10fbd7dc-8bd4-11e7-89a3-7f7e2ea457ac.png)

但是在openClientId:'xx' 后面有调用
```
if ([self.socketWrapper isConnectionOpen]) {
                [self sendOpenCommand];
            } else {
                [self.socketWrapper openWebSocketConnectionWithCallback:^(BOOL succeeded, NSError *error) {
                    [self changeStatus:AVIMClientStatusNone];
                    [AVIMBlockHelper callBooleanResultBlock:callback error:error];
                    self.openCommand.callback = nil;
                }];
            }
```
不知道这是出于什么考虑，感觉野指针就是这里两次调用出现的。

**Comment by zapcannon87** [comment]
已在 v8.0.6 中修复该问题。
