### ISSUE TITLE
建议 wiki 中的 Installation 和文档一致

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#34]
文档位置：
https://leancloud.cn/docs/sdk_setup-ios.html

现在 SDK 的安装分「源码集成」和「预编译 framework」，「源码集成」又分「自动安装」和「手动安装」。
这些概念有什么不同，又各有什么优劣，建议在文档中讲清楚，然后 wiki 中也写同样的一份。减少开发者在集成 SDK 时的困难程度。

**Comment by tang3w** [comment]
打算把安装方式组织成这样：

* 使用 CocoaPods 集成
* 集成 framework
    * 集成 AVOS.xcodeproj
    * 手动编译

我们不再提供「预编译 framework」，转而让用户「手动编译」。
