### ISSUE TITLE
获取设备的运营商失败时不要上传空字符串

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#350]
https://forum.leancloud.cn/t/topic/15964/2

背景：
有时候设备会存在获取运营商失败的情况，导致上传的为空字符串。

改进：
SDK 统一上报前，做一下判断，如果是 “” 字符串，设置为`unknown`再传。

**Comment by tang3w** [comment]
服务端做一下兼容是不是更合适？这样也可以对旧版本 SDK 生效。

**Comment by BinaryHB** [comment]
这是一个前后端相互约定，传数据的标准问题。

如果客户端传这种非法数据过大， 统计端要做大量的校验订正。

所以客户端也需要主动的保证，上传数据的合法性。
