### ISSUE TITLE
当收到奇怪的消息时，提升 SDK 的健壮性，使其不要崩溃

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#36]
![8 pic](https://cloud.githubusercontent.com/assets/10130959/17998812/bbbb37dc-6ba8-11e6-8ced-63c6b7bff8da.jpg)

有用户反馈，收到这种消息，App 就崩溃了，之前社区也遇到过类似的问题。
我们现在有三个平台的产品，代码上都稍有一些差异，发送的消息 object 都可能会产生一些差异，所以 iOS SDK 需要提升健壮性，在奇怪的消息做处理，使其不要崩溃。

**Comment by nicecui** [comment]
这个问题有待确认一下。
新的信息是，这种类型的消息不会崩溃掉。
但社区上有一个会崩溃的，我稍后找一下链接。

**Comment by ChenYilong** [comment]
这种消息，有校验，不会崩溃     https://github.com/leancloud/objc-sdk/blob/c94a171f46310618a4753206a47eec31ba8cb874/AVOS/AVOSCloudIM/AVIMClient.m#L769

**Comment by tang3w** [comment]
尽量让用户提供一个可复现问题的 Demo，可以提供最详细的线索。

**Comment by nicecui** [comment]
https://forum.leancloud.cn/t/topic/9970
看了下社区的问题，应该是 Android 传错了值。
而最初始的问题反馈还在确认中，这个 issue 先关闭吧。
