### ISSUE TITLE
error: 'sqlite3.h file not found' in LCDatabase.h

### ISSUE THREAD

**Issue by developforapple** [leancloud/objc-sdk#381]
Podfile:
use_frameworks!
platform:ios, '8.0'
target 'App' do 
pod 'FMDB/standalone'
pod 'AVOSCloud'
end

无法通过编译。原因'FMDB/standalone'使用最新的sqlite3。
在 FMDatabase.m 中有这样的代码：
    #if FMDB_SQLITE_STANDALONE
    #import <sqlite3/sqlite3.h>
    #else
    #import <sqlite3.h>
    #endif

可手动修改 AVOSCloud target 来通过编译：
1 Build Phases/Target Dependencies 中添加sqlite3.framework
2 Build Phases/Link Binary With Libraries 中添加 sqlite3.framework
3 Build Settings/Search Paths/Framework Search Paths 添加值 "$PODS_CONFIGURATION_BUILD_DIR/sqlite3"

**Comment by tang3w** [comment]
谢谢反馈，好像 SDK 不能做什么。特殊情况就先特殊处理一下吧。

**Comment by developforapple** [comment]
FMDB的podspec中添加了这样的subspecs:

    s.subspec 'standalone' do |ss|
    ss.xcconfig = { 'OTHER_CFLAGS' => '$(inherited) -DFMDB_SQLITE_STANDALONE' }
    ss.dependency 'sqlite3'
    ss.source_files = 'src/fmdb/FM*.{h,m}'
    ss.exclude_files = 'src/fmdb.m'
    end

在FMDatabase.m中使用宏 DFMDB_SQLITE_STANDALONE 来判断是否使用最新版的sqlite3。

apple默认的sqlite3版本比较旧。所以采用最新版或许是一种提高性能的手段。

AVOSCloud如果可以也加一个使用最新版sqlite3的subspec就最好了。

**Comment by tang3w** [comment]
谢谢建议。SDK 可能还是默认连接默认的 sqlite 比较合适，毕竟不一定所有开发者都希望使用 standalone 的版本。

**Comment by chn-lyzhi** [comment]
一样的问题，GRDB.swift 和 AVOSCloud 冲突。问题是 sqlite3.framework 从哪来？
