### ISSUE TITLE
为什么AVFile 的 getDataStreamInBackgroundWithBlock:progressBlock: 方法中error总是nil

### ISSUE THREAD

**Issue by developforapple** [leancloud/objc-sdk#397]
下面是 getDataStreamInBackgroundWithBlock:progressBlock: 方法的实现。
为什么 resultBlock的error参数总是传nil?

[self downloadFileImpl:^(BOOL succeeded, NSError *error) {
        NSString *path = self.localPath;
        NSInputStream * inputStream = [[NSInputStream alloc] initWithFileAtPath:path];
        if (resultBlock) resultBlock(inputStream, nil);
    } progressBlock:^(NSInteger percentDone) {
        if (progressBlock) progressBlock(percentDone);
    }];

**Comment by zapcannon87** [comment]
感谢您的反馈，看起来应该是 SDK 的 bug，我们会在下个版本修复该问题。
