### ISSUE TITLE
currentUser 直接打印时，没有 createdAt、updatedAt、objectId 等等字段

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#4]
### 用户需求：
比如 Android 用户打印 AVUser.getCurrentUser().toString() 时，除了 password 字段外，其他都可以看到。这样自然就使用 get() 方法，拿自己想要的字段即可。

### Obj-C 现况：
直接打印 currentUser 是取内存的 localData 数据。需要使用 [currentUser dictionaryForObject] 打印才能打印出所有字段。

### 绕过方案：
尽管有点反直觉，但是用户调用 currentUser.createdAt 是可以直接拿到属性的。

---
不知道这里是否需要改进一下？从 Obj-C 开发的角度而言是否合理？ @tang3w

**Comment by tang3w** [comment]
的确应该改进一下，优先级不高，后面几个版本来做。

**Comment by tang3w** [comment]
Solved in #7 @BinaryHB
