### ISSUE TITLE
8.0.4 执行登录用户报错

### ISSUE THREAD

**Issue by SLboat** [leancloud/objc-sdk#402]
执行代码
` let _ = try? AVUser.logIn(withUsername:username, password: password, error: ())`

出错提醒

+[NSDictionary lc_isInvalidForCheckingTypeWith:]: unrecognized selector sent to class 0x1b5a80b80

**Comment by zapcannon87** [comment]
您好，请问这个问题是必然出现的吗？我这边测试好像没问题。

**Comment by SLboat** [comment]
@zapcannon87 奇怪了,这里每次都出现唉,注销用户后再来就必然丢错

**Comment by zapcannon87** [comment]
注销是指 AVUser 的正常登出，还是指销毁这个已经注册过的 AVUser ？

**Comment by SLboat** [comment]
卸载一个安装的程序,然后是一个全新的实例这样,奇怪了,难道是我这里的个例

**Comment by zapcannon87** [comment]
您自己的代码有对 NSDictionary 这个 Cocoa 基础类做过修改吗，或者引入的其它第三方库对 NSDictionary 或 NSObject 做过修改？

**Comment by SLboat** [comment]
@zapcannon87 效率真及时!没有噢,就是在Swift下调用,请问工程师你也尝试是Swift下调用吗?

**Comment by zapcannon87** [comment]
是的，我在 Swift 调用是没问题的，master 里有个 [测试用例](https://github.com/leancloud/objc-sdk/blob/9a4f4cf01c3d4f5177a5164dde354b9b2deb1434/AVOS/AVOSCloudTests/Swift/AVUserTestCase.swift#L23) 。测试完是正常的。

lc_isInvalidForCheckingTypeWith 是给 NSObject 加的一个类方法，如果其它的代码没有用 runtime 修改过基础类，那么该方法是不应该找不到的。

**Comment by SLboat** [comment]
@zapcannon87 感谢你的及时跟进!抱歉我的描述太武断了,我从头构建一个项目,测试下是否出现这个问题,如果出现我提交源码给你,我想能提供更可靠的描绘问题本身!

**Comment by SLboat** [comment]
@zapcannon87 https://github.com/SLboat/TESTAVOSCloud 新项目能够复现问题,必须登录成功的用户,请测试下,打包的是8.0.4 的release库

**Comment by zapcannon87** [comment]
@SLboat 好的。

**Comment by SLboat** [comment]
![slboat-mac-screen 2017-12-11 18 46 49](https://user-images.githubusercontent.com/4231376/33827539-53be5b60-de2e-11e7-81e0-42f069d59f19.jpg)
我直接使用源码来运行也是出错的,很奇怪

**Comment by SLboat** [comment]
稍微更新了下源码,现在是直接用leancloud的源码跑的,请看下.

**Comment by SLboat** [comment]
@zapcannon87  好像明白了,必须在实际项目里的Other Linker Flags加入[-ObjC]才能找到这个类方法,似乎是8.0某个版本后单独移出来的这个扩展?

**Comment by zapcannon87** [comment]
嗯，应该是这样的，感谢您的反馈。

**Comment by SLboat** [comment]
感谢!
