### ISSUE TITLE
迫切需要一个后台上传的接口

### ISSUE THREAD

**Issue by ancoo** [leancloud/objc-sdk#41]
批量上传时候进入后台就停止了
不知道有没有这方面的开发计划
好姜

**Comment by tang3w** [comment]
请问应用有没有开启后台运行？

**Comment by ancoo** [comment]
@tang3w 
我在capabilities里点了background mode
![2016-09-04 11 10 41](https://cloud.githubusercontent.com/assets/7137186/18228795/43e52184-7290-11e6-8937-5cb703bb75d0.png)
其他还需要特殊设置吗？

**Comment by tang3w** [comment]
还需要结合 Background Task 来完成。可以在 AppDelegate 中实现以下方法：

```objc
- (void)applicationDidEnterBackground:(UIApplication *)application {
    UIBackgroundTaskIdentifier backgroundTask = [application beginBackgroundTaskWithExpirationHandler:^{
        [application endBackgroundTask:backgroundTask];
    }];
}
```
