### ISSUE TITLE
通过 User 登录 IM 后再登出会导致 crash

### ISSUE THREAD

**Issue by tang3w** [leancloud/objc-sdk#434]
用户报告当以 LCIMClientLoginMethodUser 登录 IM 后再登出，会 crash：
![521516784832_ pic_hd](https://user-images.githubusercontent.com/2226563/35323791-bf415568-0129-11e8-9f8e-8dd8d1c83077.jpg)
原因是此处的 _clientId 为 nil：
![541516784863_ pic](https://user-images.githubusercontent.com/2226563/35323900-1bcb659e-012a-11e8-9bf6-414b0066bf2c.jpg)

**Comment by zapcannon87** [comment]
这是一个已知的问题，已经修复了，只是还没发版。

ref：https://github.com/leancloud/paas/issues/986

**Comment by tang3w** [comment]
要不先简单处理一下这个 crash 发个版本？

**Comment by zapcannon87** [comment]
好，明天发个修复版吧。

**Comment by zapcannon87** [comment]
ref: https://github.com/leancloud/objc-sdk/pull/435
