### ISSUE TITLE
可否考虑支持一下Carthage

### ISSUE THREAD

**Issue by RyukieSama** [leancloud/objc-sdk#439]
最近准备使用 Carthage 替代 CocoaPods
但是这SDK无法用 Carthage 导入
提示:
Skipped building R.swift due to the error:
Dependency "R.swift" has no shared framework schemes for any of the platforms: iOS

**Comment by zapcannon87** [comment]
> Dependency "R.swift" has no shared framework schemes

这是 「R.swift」这个库的错误吧，好像和我们的 sdk 没有什么关系？
我们近期并没有支持 Carthage 的计划。未来会考虑是否去支持 Carthage。

**Comment by RyukieSama** [comment]
报错信息复制错了...
