### ISSUE TITLE
support iOS 10 Remote Notification 

### ISSUE THREAD

**Issue by ChenYilong** [leancloud/objc-sdk#45]
Ref: https://forum.leancloud.cn/t/ios-10/10892

**Comment by tang3w** [comment]
iOS SDK 目前已经支持自定义 payload 格式。有哪些需要做的工作？

**Comment by tang3w** [comment]
@ChenYilong 这个 issue 是否可以关闭了？

**Comment by ChenYilong** [comment]
这个issue服务端已经支持了，关了吧。
