### ISSUE TITLE
[currentUser dictionaryForObject] 会明文打印出 user 密码

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/objc-sdk#5]
如下图：

![_2016-07-15_16-21](https://cloud.githubusercontent.com/assets/6046086/16869552/f6cca3e8-4aaf-11e6-8a42-5e6fca99ae1b.png)

希望可以在本地打印时，去掉 password 这个字段，安全性高得多。

**Comment by tang3w** [comment]
预计在 v3.4.1 中修复。

**Comment by tang3w** [comment]
Solved in #7 @BinaryHB
