### ISSUE TITLE
webSocket reopen error

### ISSUE THREAD

**Issue by devjiangzhou** [leancloud/objc-sdk#540]
@zapcannon87 

SDK 11.4.8 版本
复现路径：
1.  进入后台中断，返回前台
2. 切换网络

现象：调用 imClientResuming 后就没有 不会调用 imClientResumed 或者 imClientClosed

日志打印的连接错误

[❤️ERROR] -[AVIMClient webSocketWrapperDidReopen:]_block_invoke_3 [Line 942] session resuming failed with error: Error Domain=com.LeanCloud.ErrorDomain Code=9003 "Web Socket command received from server is invalid." UserInfo={NSLocalizedFailureReason=Web Socket command received from server is invalid.}

**Comment by devjiangzhou** [comment]
[❤️ERROR] -[AVIMClient webSocketWrapperDidReopen:]_block_invoke_3 [Line 942] session resuming failed with error: Error Domain=com.LeanCloud.ErrorDomain Code=9003 "Web Socket command received from server is invalid." UserInfo={NSLocalizedFailureReason=Web Socket command received from server is invalid.}

**Comment by zapcannon87** [comment]
您的代码里是否有「多个情形会调用 open 方法」？比如您监控了网络状态，在网络状态恢复时，调用了 open 方法。

正常来说，open 方法只要调用成功过一次，SDK 就会开启自动重连。是无需再次调用 open 方法的。

**Comment by devjiangzhou** [comment]
@zapcannon87  必现的。 没有多次调用 open 的。

**Comment by devjiangzhou** [comment]
// 我们 APP 
   cmd: session
    op: opened
    appId: "xxx"
    peerId: "xxxx"
    i: 4
    service: 2
    sessionMessage {
    }

// ChatKit
content: <AVIMGenericCommand 0x10771ca10>: {
    cmd: session
    op: opened
    appId: "dYRQ8YfHRiILshUnfFJu2eQM-gzGzoHsz"
    peerId: "123"
    i: 6
    service: 2
    sessionMessage {
      st: "RiILshUnfFJu2eQM-gzGzoHszyjUPsFRlSbKqjTxd53uoug"
      stTtl: 17280
    }
}

@zapcannon87  就是因为 sessionMessage 为空 导致的。

**Comment by zapcannon87** [comment]
能提供一下 out command 的信息吗？`cmd: session op: open` 的。

**Comment by devjiangzhou** [comment]
content: <AVIMGenericCommand 0x110f1a470>: {
    cmd: session
    op: open
    appId: "xxxxxx"
    peerId: "xxxx"
    i: 4
    sessionMessage {
      r: true
      st: "bx10kqqgi45s2mxo9jzq0k60xhlha1152z80v3zlff4dfc094f58bd8185251014HtMhMwfUTqSDVEu5U5azzQ"
    }
}

这是我的代码：
https://gist.github.com/devjiangzhou/ea65d2d147910177d65babae4013a010

**Comment by zapcannon87** [comment]
从您的给的信息来看，这个 out command 是由 SDK 在做自动重连时发出的。您能给出所有的 log 信息吗？单从这个看不出上下文的联系。

可以邮件发送给我，邮箱见我的 GitHub 主页。
