### ISSUE TITLE
手动集成 SDK 文档中的「编译 framework」模块内容失效

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/objc-sdk#542]
「编译 framework」这种方式已经报错找不到目录，暂时的解决办法是，先从文档中下掉这部分。

更新修复后再补充正确内容到文档中。

![image](https://user-images.githubusercontent.com/11917002/50440531-a652c300-0931-11e9-94d6-0e3e7232176f.png)

**Comment by zapcannon87** [comment]
no need
