### ISSUE TITLE
saveInBackgroundWithBlock 报错esponse Code=-1016 "Request failed: unacceptable content-type: text/plain"

### ISSUE THREAD

**Issue by WJHCode** [leancloud/objc-sdk#578]
[currentInstallation saveInBackgroundWithBlock:^(BOOL succeeded, NSError * _Nullable error) {
        if (succeeded) {
            NSLog(@"");
        };
    }];

报错 error:
response: Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/plain"

**Comment by zapcannon87** [comment]
能否提供 SDK 版本号？

**Comment by WJHCode** [comment]
AVOSCloud 12.0.1 (was 12.0.0)
这两个版本的SDK都是同样的问题，我之前用的旧版本的还是OK的。
push已经注册成功，并且deviceToken已经返回了，就是这个保存的时候失败

**Comment by WJHCode** [comment]
设置deviceTokenData,
旧版本使用的接口是- (void)setDeviceTokenFromData:(NSData *)deviceTokenData
新版本（12.0.1 (was 12.0.0)）接口变成了，- (void)setDeviceTokenFromData:(NSData *)deviceTokenData teamId:(NSString *)teamId

**Comment by zapcannon87** [comment]
我这边真机测试是没问题。

可以的话，请提供详细的 log 信息，以便我们排查问题（邮件发给我即可）。
