### ISSUE TITLE
这么大的bug都不自测一下吗？升级到12.0.0之后，必crash。

### ISSUE THREAD

**Issue by oszone** [leancloud/objc-sdk#589]
闪退如下：
![image](https://user-images.githubusercontent.com/45854216/69472775-51d9f100-0de9-11ea-828e-0e2ebc0f76c3.png)

注册启动注册sdk时，直接闪退。
![image](https://user-images.githubusercontent.com/45854216/69472804-92d20580-0de9-11ea-818b-155837841580.png)

**Comment by zapcannon87** [comment]
请问这是在 macOS 环境下出现的？

**Comment by oszone** [comment]
> 请问这是在 macOS 环境下出现的？

是的。
