### ISSUE TITLE
Crash in conversationsForCommand

### ISSUE THREAD

**Issue by Monkeyzc** [leancloud/objc-sdk#592]
Our app sometimes crash in conversationsForCommand when app start. Here is Fabric Crashlytics report. AVOSCloud  and AVOSCloudIM version is 10.3.1
<img width="1097" alt="截屏2019-11-28上午11 13 04" src="https://user-images.githubusercontent.com/16532120/69774306-888c7e80-11d0-11ea-8872-c31c4cf0d86c.png">
<img width="1096" alt="截屏2019-11-28上午11 13 13" src="https://user-images.githubusercontent.com/16532120/69774315-8f1af600-11d0-11ea-99f7-945bc7882d01.png">

**Comment by zapcannon87** [comment]
it has been fixed in [the latest version](https://github.com/leancloud/objc-sdk/releases).
