### ISSUE TITLE
LCURLSessionManager af_resume conflict with AFN

### ISSUE THREAD

**Issue by Monkeyzc** [leancloud/objc-sdk#593]
Can you explain why use af_resume and af_suspend. That can make app crash, I think it coflict with AFN.
<img width="1074" alt="截屏2019-12-01下午7 35 30" src="https://user-images.githubusercontent.com/16532120/69913410-4a15ee80-1472-11ea-86ff-36a88aab02dd.png">

**Comment by zapcannon87** [comment]
which version you used? 

can you provide more info about crash? like stack trace.
