### ISSUE TITLE
Breakpad crashReport

### ISSUE THREAD

**Issue by shaohung001** [leancloud/objc-sdk#60]
请问在CrashReporting项目中，Breakpad里面全部没有文件，能否提供如何加入CrasgReporting的功能

**Comment by tang3w** [comment]
请参考 [手动安装的文档](https://leancloud.cn/docs/sdk_setup-ios.html#手动安装) 来了解详细的步骤。

**Comment by shaohung001** [comment]
非常感谢，阅读文档太快直接忽略那段话了，，，表示那个在download下来的文件不能直接执行update操作，得git clone下来的framework才能update，，整了一下午，，，终于整上去了
