### ISSUE TITLE
考虑 SDK 不再提供注册 device token 的方法

### ISSUE THREAD

**Issue by tang3w** [leancloud/objc-sdk#63]
理由如下：

1. 注册 device token 的接口在 iOS 7, 8, 10 中均不一样，会充斥版本检测的代码，不利于维护；
2. 参数的类型均不一样，封装成统一的方法意味着将类型弱化，而且还要假设枚举值相等，是易碎的。

因此建议废除所有注册 device token 的快捷方法。转而在文档中提示。

@leancloud/ios-group

**Comment by ChenYilong** [comment]
嗯，可以，文档我来写下。
