### ISSUE TITLE
conversation 带上 lastMessage

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#86]
query conversation 时一并返回这个 conversation 的 lastMessage

**Comment by ChenYilong** [comment]
Reference：https://github.com/leancloud/objc-sdk/issues/87

**Comment by ChenYilong** [comment]
https://github.com/leancloud/paas/issues/797

**Comment by ChenYilong** [comment]
PR：https://github.com/leancloud/objc-sdk/pull/110

**Comment by tang3w** [comment]
已在 v3.10.0 中实现。
