### ISSUE TITLE
conversation 支持已读/未读消息

### ISSUE THREAD

**Issue by nicecui** [leancloud/objc-sdk#92]

**Comment by ChenYilong** [comment]
Read标记讨论： https://github.com/leancloud/avoscloud-push/issues/675

**Comment by ChenYilong** [comment]
//TODO:


* [ ] 升级传输协议
   lc.json.3 同2，但 ack 和 read 分离, ack 不会清理未读消息
   lc.msgpack.3 同2，但 ack 和 read 分离, ack 不会清理未读消息
   lc.protobuf.3 同2，但 ack 和 read 分离, ack 不会清理未读消息
* [ ] 缓存兼容
* [ ] 添加单元测试

**Comment by ChenYilong** [comment]
PR:https://github.com/leancloud/objc-sdk/pull/112

**Comment by tang3w** [comment]
Implemented in 4.3.0
