### ISSUE TITLE
Support to set custom property for conversation

### ISSUE THREAD

**Issue by tang3w** [leancloud/objc-sdk#98]
https://github.com/leancloud/paas/issues/846

**Comment by ChenYilong** [comment]
现在问题出在如何从Protobuf的库中找到合适的API去做这件事情：

原生就有C语言风格的Getter和setter。 比如数组类型的：`GPBSetMessageRepeatedField`、 `GPBGetMessageRepeatedField ` ，但只能**修改**不能**添加**。该API都依赖于初始化时已存在于`fields_`数组中的元素，未找到往`fields_`添加元素的API。

我看了下API，能给一个Message对象动态添加Field的相关API有如下：

API | 说明
-------------|-------------
 `GPBUnknownFieldSet` | 仅支持protobuf2，现在使用的是3，所以不能使用
`GPBExtensionDescriptor` | 仅支持protobuf2，现在使用的是3，所以不能使用

Reference：

 1.  [官方文档extensions部分](https://developers.google.com/protocol-buffers/docs/reference/objective-c-generated#extensions) 明确说明只支持只支持protobuf2.

 2. [[feature request] Support setting values via field descriptors in the Objective C Descriptor API #1981](https://github.com/google/protobuf/issues/1981)  中的确

 3. [How to get custom field option? [objc] #1779](https://github.com/google/protobuf/issues/1779) 

 4.  [官方文档](https://developers.google.com/protocol-buffers/docs/reference/objective-c-generated#wellknown) 倒是新添加了新的数据类型，但是是有限的几个。
 



@leancloud/ios-group

**Comment by tang3w** [comment]
如果 protobuf 3 没有相应的 API，是不是可以考虑降级到 protobuf 2？
另外，还有一个潜在的问题是：目前 Conversation 缓存固定的属性，动态添加的字段无法缓存下来。

@daweibayu Android 这边也是依赖 protobuf 的 API 吗？另外，缓存的问题是如何解决的？

**Comment by daweibayu** [comment]
这个应该不需要修改 protobuf 什么东西，原来的 protocol 就是支持 attr 的，只不过原来的的数据是 {"attr":"xxx"}，而现在的是 {"attr":"xxxx" , "key":"xxxx"} 。
关于缓存，刚看了一下，Android 这边的处理也是有缺失的，这里还需要补充一下。

**Comment by ChenYilong** [comment]
嗯了解。

**Comment by ChenYilong** [comment]
`-[AVIMClient createConversationWithName:clientIds:attributes:options:callback:]`  创建对话时用户添加的属性，也是调用这次setter方法做的吗，还是说此种情况下，维持原状，统一放在`attr`下面？@daweibayu
